// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package courierProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CourierServerClient is the client API for CourierServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourierServerClient interface {
	CreateOrder(ctx context.Context, in *OrderCourierServer, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetDeliveryServicesList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServicesResponse, error)
}

type courierServerClient struct {
	cc grpc.ClientConnInterface
}

func NewCourierServerClient(cc grpc.ClientConnInterface) CourierServerClient {
	return &courierServerClient{cc}
}

func (c *courierServerClient) CreateOrder(ctx context.Context, in *OrderCourierServer, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/courier.CourierServer/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierServerClient) GetDeliveryServicesList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServicesResponse, error) {
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, "/courier.CourierServer/GetDeliveryServicesList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourierServerServer is the server API for CourierServer service.
// All implementations must embed UnimplementedCourierServerServer
// for forward compatibility
type CourierServerServer interface {
	CreateOrder(context.Context, *OrderCourierServer) (*emptypb.Empty, error)
	GetDeliveryServicesList(context.Context, *emptypb.Empty) (*ServicesResponse, error)
	mustEmbedUnimplementedCourierServerServer()
}

// UnimplementedCourierServerServer must be embedded to have forward compatible implementations.
type UnimplementedCourierServerServer struct {
}

func (UnimplementedCourierServerServer) CreateOrder(context.Context, *OrderCourierServer) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedCourierServerServer) GetDeliveryServicesList(context.Context, *emptypb.Empty) (*ServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveryServicesList not implemented")
}
func (UnimplementedCourierServerServer) mustEmbedUnimplementedCourierServerServer() {}

// UnsafeCourierServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourierServerServer will
// result in compilation errors.
type UnsafeCourierServerServer interface {
	mustEmbedUnimplementedCourierServerServer()
}

func RegisterCourierServerServer(s grpc.ServiceRegistrar, srv CourierServerServer) {
	s.RegisterService(&CourierServer_ServiceDesc, srv)
}

func _CourierServer_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCourierServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServerServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/courier.CourierServer/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServerServer).CreateOrder(ctx, req.(*OrderCourierServer))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourierServer_GetDeliveryServicesList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServerServer).GetDeliveryServicesList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/courier.CourierServer/GetDeliveryServicesList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServerServer).GetDeliveryServicesList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CourierServer_ServiceDesc is the grpc.ServiceDesc for CourierServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourierServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "courier.CourierServer",
	HandlerType: (*CourierServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _CourierServer_CreateOrder_Handler,
		},
		{
			MethodName: "GetDeliveryServicesList",
			Handler:    _CourierServer_GetDeliveryServicesList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order-cs.proto",
}
