// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package orderservice_fd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceFDClient is the client API for OrderServiceFD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceFDClient interface {
	UpdateOrder(ctx context.Context, in *UpdateOrderMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type orderServiceFDClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceFDClient(cc grpc.ClientConnInterface) OrderServiceFDClient {
	return &orderServiceFDClient{cc}
}

func (c *orderServiceFDClient) UpdateOrder(ctx context.Context, in *UpdateOrderMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/OrderServiceFD/UpdateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceFDServer is the server API for OrderServiceFD service.
// All implementations must embed UnimplementedOrderServiceFDServer
// for forward compatibility
type OrderServiceFDServer interface {
	UpdateOrder(context.Context, *UpdateOrderMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedOrderServiceFDServer()
}

// UnimplementedOrderServiceFDServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceFDServer struct {
}

func (UnimplementedOrderServiceFDServer) UpdateOrder(context.Context, *UpdateOrderMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (UnimplementedOrderServiceFDServer) mustEmbedUnimplementedOrderServiceFDServer() {}

// UnsafeOrderServiceFDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceFDServer will
// result in compilation errors.
type UnsafeOrderServiceFDServer interface {
	mustEmbedUnimplementedOrderServiceFDServer()
}

func RegisterOrderServiceFDServer(s grpc.ServiceRegistrar, srv OrderServiceFDServer) {
	s.RegisterService(&OrderServiceFD_ServiceDesc, srv)
}

func _OrderServiceFD_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceFDServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrderServiceFD/UpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceFDServer).UpdateOrder(ctx, req.(*UpdateOrderMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderServiceFD_ServiceDesc is the grpc.ServiceDesc for OrderServiceFD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderServiceFD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OrderServiceFD",
	HandlerType: (*OrderServiceFDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateOrder",
			Handler:    _OrderServiceFD_UpdateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order-fd.proto",
}
