// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: order-fd.proto

package orderservice_fd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateOrderMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderUUID string `protobuf:"bytes,1,opt,name=OrderUUID,proto3" json:"OrderUUID,omitempty"`
	Status    int64  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *UpdateOrderMessage) Reset() {
	*x = UpdateOrderMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_fd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderMessage) ProtoMessage() {}

func (x *UpdateOrderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_order_fd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderMessage.ProtoReflect.Descriptor instead.
func (*UpdateOrderMessage) Descriptor() ([]byte, []int) {
	return file_order_fd_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateOrderMessage) GetOrderUUID() string {
	if x != nil {
		return x.OrderUUID
	}
	return ""
}

func (x *UpdateOrderMessage) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_order_fd_proto protoreflect.FileDescriptor

var file_order_fd_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2d, 0x66, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a,
	0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x55, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x4e, 0x0a, 0x0e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x44, 0x12, 0x3c, 0x0a, 0x0b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x66, 0x64, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x66, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_fd_proto_rawDescOnce sync.Once
	file_order_fd_proto_rawDescData = file_order_fd_proto_rawDesc
)

func file_order_fd_proto_rawDescGZIP() []byte {
	file_order_fd_proto_rawDescOnce.Do(func() {
		file_order_fd_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_fd_proto_rawDescData)
	})
	return file_order_fd_proto_rawDescData
}

var file_order_fd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_fd_proto_goTypes = []interface{}{
	(*UpdateOrderMessage)(nil), // 0: UpdateOrderMessage
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
}
var file_order_fd_proto_depIdxs = []int32{
	0, // 0: OrderServiceFD.UpdateOrder:input_type -> UpdateOrderMessage
	1, // 1: OrderServiceFD.UpdateOrder:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_fd_proto_init() }
func file_order_fd_proto_init() {
	if File_order_fd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_fd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_fd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_fd_proto_goTypes,
		DependencyIndexes: file_order_fd_proto_depIdxs,
		MessageInfos:      file_order_fd_proto_msgTypes,
	}.Build()
	File_order_fd_proto = out.File
	file_order_fd_proto_rawDesc = nil
	file_order_fd_proto_goTypes = nil
	file_order_fd_proto_depIdxs = nil
}
